version: '3.8'
services:
  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    container_name: user-service
    networks:
      - app-network

  order-service:
    build: ./order-service
    ports:
      - "3002:3002"
    container_name: order-service
    depends_on:
      - user-service
    networks:
      - app-network

  payment-service:
    build: ./payment-service
    ports:
      - "3003:3003"
    container_name: payment-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge