apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  annotations:
    konghq.com/plugins: kong-rate-limit-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: order-service:1.0.30
          imagePullPolicy: Never
          ports:
            - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  annotations:
    konghq.com/plugins: kong-rate-limit-order
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
