apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  annotations:
    konghq.com/plugins: kong-rate-limit-payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: payment-service:1.0.32
          imagePullPolicy: Never
          ports:
            - containerPort: 3003
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  annotations:
    konghq.com/plugins: kong-rate-limit-payment
spec:
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
