apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  annotations:
    konghq.com/plugins: kong-rate-limit-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: user-service:1.0.30
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  annotations:
    konghq.com/plugins: kong-rate-limit-order
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
